In [51]:
from geopy.geocoders import Nominatim
import pandas as pd
import numpy as np
data = pd.read_csv("Nepal_GeoData.csv",sep=",")

In [9]:
df = data
df['neighborhood']=""
df['city']=""
df['state']=""
df['areadetail']=""
df['route']=""
df['zipcode']=""

In [13]:
df = df.loc[0:99999]

In [14]:
df.describe()

,d.id_str,d.favorite_count,d.in_reply_to_status_id_str,d.retweet_count,d.user.id_str,d.in_reply_to_user_id_str,d.user.followers_count,d.user.statuses_count,d.user.utc_offset,d.user.friends_count,d.user.favourites_count,d.user.listed_count,d.quoted_status_id_str,geo.lat,geo.lon,timezone
count,1.000000e+05,100000.000000,3.560500e+04,100000.000000,1.000000e+05,3.956300e+04,1.000000e+05,1.000000e+05,68207.000000,100000.000000,100000.000000,100000.000000,6.900000e+02,100000.000000,100000.000000,68207.000000
mean,5.938533e+17,1.735170,5.924660e+17,0.729550,1.366362e+09,1.359464e+09,5.923668e+03,2.816201e+04,11045.429355,1924.566110,15324.366280,31.824850,5.902473e+17,27.283026,83.057575,3.068175
std,1.643609e+16,8.185983,1.900072e+16,6.321828,1.131682e+09,1.157186e+09,4.255218e+04,7.015970e+04,18816.875126,4599.475018,28488.145277,218.262545,6.685889e+16,5.600532,18.461498,5.226910
min,5.696492e+17,0.000000,2.420247e+10,0.000000,6.335230e+05,7.170000e+02,0.000000e+00,1.000000e+00,-39600.000000,0.000000,0.000000,0.000000,2.266093e+09,-38.452700,-157.862300,-11.000000
25%,5.810203e+17,0.000000,NaN,0.000000,2.899686e+08,NaN,5.420000e+02,2.992000e+03,NaN,289.000000,699.000000,3.000000,NaN,27.668300,84.399000,NaN
50%,5.905514e+17,1.000000,NaN,0.000000,1.011679e+09,NaN,1.656000e+03,1.156200e+04,NaN,607.000000,4833.000000,9.000000,NaN,27.696800,85.312300,NaN
75%,6.049992e+17,1.000000,NaN,0.000000,2.584452e+09,NaN,4.880000e+03,2.732900e+04,NaN,1736.000000,18546.000000,21.000000,NaN,27.734200,85.348600,NaN
max,6.314649e+17,1434.000000,6.314648e+17,755.000000,3.398688e+09,3.381717e+09,8.430430e+06,1.293323e+06,46800.000000,59900.000000,284051.000000,18729.000000,6.313990e+17,67.868000,153.064300,13.000000

In [15]:
import requests
import urllib, json


def getaddress(latitude,longitude):
    sensor = 'true'
    base = "https://maps.googleapis.com/maps/api/geocode/json?"
    params = "latlng={lat},{lon}&key={apikey}".format(
        lat=latitude,
        lon=longitude,
        apikey = "AIzaSyAHFps2OwwfdySoSFv6SNCgNfC6tKiIWu0"
    )
    url = "{base}{params}".format(base=base, params=params)
    
    response = urllib.urlopen(url)
    data = json.loads(response.read())
    return data['results'][0]['address_components']

In [58]:
import requests
import urllib, json


def get_areaaddress(latitude,longitude):
    sensor = 'true'
    base = "http://photon.komoot.de/reverse?"
    params = "lat={lat}&lon={lon}".format(
        lat = latitude,
        lon = longitude
    )
    url = "{base}{params}".format(base=base, params=params)
    print url
    response = urllib.urlopen(url)
    data = json.loads(response.read())
    return data['features']

In [61]:
data.pincode.describe()

count     214556
unique       937
top
freq      213429
Name: pincode, dtype: object

In [59]:
data['pincode']=""
for row in data.index:
    data.loc[row,'pincode'] = get_areaaddress(data.loc[row,'geo.lat'],data.loc[row,'geo.lon'])

ValueError: Must have equal len keys and value when setting with an iterable

In [35]:
zones = ['Mechi','Koshi','Sagarmatha','Janakpur','Bagmati','Narayani','Gandaki','Lumbini','Dhaulagiri','Rapti','Karnali','Bheri','Seti','Mahakali']
get_areaaddress('Mechi')

https://maps.googleapis.com/maps/api/geocode/json?components=administrative_area_2:Mechi|country:NP&key=AIzaSyAHFps2OwwfdySoSFv6SNCgNfC6tKiIWu0
[{u'geometry': {u'location_type': u'APPROXIMATE', u'bounds': {u'northeast': {u'lat': 30.4469452, u'lng': 88.20152569999999}, u'southwest': {u'lat': 26.3479661, u'lng': 80.05846980000001}}, u'viewport': {u'northeast': {u'lat': 30.4469452, u'lng': 88.20152569999999}, u'southwest': {u'lat': 26.3479661, u'lng': 80.05846980000001}}, u'location': {u'lat': 28.394857, u'lng': 84.12400799999999}}, u'address_components': [{u'long_name': u'Nepal', u'types': [u'country', u'political'], u'short_name': u'NP'}], u'place_id': u'ChIJz2gufcfolTkR3obM0LyaojQ', u'formatted_address': u'Nepal', u'types': [u'country', u'political']}]

In [16]:
def elementextract(addressjson,address_type):
        i = 0
        while True:
            if addressjson[i]["types"][0]==address_type:
                return addressjson[i]["long_name"]
            else:
                i = i+1

In [17]:
with open("citycoor.csv",'a') as filecoor:
    for row in df.index:
        if (not(df.loc[row,'geo.lat'] is None or df.loc[row,'geo.lon'] is None)):
            try:
                addressset = getaddress(df.loc[row,'geo.lat'],df.loc[row,'geo.lon'])
            except:
                break
            try:
                t = encodeelementextract(addressset,'neighborhood')
                df.loc[row,'neighborhood'] =t
            except:
                df.loc[row,'neighborhood']=""
            try:
                t = elementextract(addressset,"locality")
                df.loc[row,'city'] =t
            except:
                df.loc[row,'city']=""
            try:
                t = elementextract(addressset,"administrative_area_level_2")
                df.loc[row,'areadetail'] =t
            except:
                df.loc[row,'areadetail']=""
            try:
                t = elementextract(addressset,"route")
                df.loc[row,'route'] =t
            except:
                df.loc[row,'route']=""
            try:
                t = elementextract(addressset,"administrative_area_level_1")
                df.loc[row,'state'] =t
            except:
                df.loc[row,'state']=""
            try:
                t = elementextract(addressset,"postal_code")
                df.loc[row,'zipcode'] =t
            except:
                df.loc[row,'zipcode']=""

In [19]:
df.head(10)

,d.favorited,d.id_str,d.favorite_count,d.in_reply_to_status_id_str,d.retweeted,d.retweet_count,d.source,d.lang,d.possibly_sensitive,d.user.id_str,...,geo.lon,hashtag_list,timezone,datetime,neighborhood,city,state,areadetail,route,zipcode
0,False,5.891146e+17,3,NaN,False,1,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,1399365542,...,85.3774,NaN,NaN,2015-04-17 17:13:57,,Madhyapur Thimi,Central Development Region,Bagmati,Dhunche Road,44600
1,False,5.894273e+17,3,NaN,False,0,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,1241134855,...,85.3403,NaN,5.75,2015-04-18 13:56:41,,Kathmandu,Central Development Region,Bagmati,Shiva marga,44600
2,False,5.897475e+17,0,5.897471e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",hi,NaN,2854219495,...,85.2833,NaN,-7.00,2015-04-19 11:09:00,,Kathmandu,Central Development Region,Bagmati,Ring Road,44600
3,False,5.896474e+17,1,5.896472e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,624532985,...,85.3333,NaN,5.75,2015-04-19 04:31:09,,Kathmandu,Central Development Region,Bagmati,Ring Road,44600
4,False,5.890443e+17,0,5.890430e+17,False,0,"<a href=""http://twitter.com/download/iphone"" r...",ne,NaN,520390791,...,85.3103,NaN,NaN,2015-04-17 12:34:51,,Kathmandu,Central Development Region,Bagmati,Chaksibari Marg,44600
5,False,5.889535e+17,1,5.889519e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,1241134855,...,85.3402,NaN,5.75,2015-04-17 06:33:43,,Kathmandu,Central Development Region,Bagmati,Seti Opi Marga,44600
6,False,5.887357e+17,1,5.887351e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,2304315770,...,85.3403,NaN,5.75,2015-04-16 16:08:15,,Kathmandu,Central Development Region,Bagmati,Seti Opi Marga,44600
7,False,5.888787e+17,0,5.888739e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",ne,NaN,1257076274,...,85.3459,NaN,5.75,2015-04-17 01:36:41,,Kathmandu,Central Development Region,Bagmati,Rishi Bhakta Marg,44600
8,False,5.890526e+17,1,NaN,False,0,"<a href=""http://twitter.com/download/android"" ...",en,False,484353307,...,85.3516,NaN,5.75,2015-04-17 13:07:49,,Kathmandu,Central Development Region,Bagmati,Boudhanath Marg,44600
9,False,5.886661e+17,1,5.886660e+17,False,0,"<a href=""http://twitter.com/download/android"" ...",et,NaN,459435447,...,85.3324,NaN,NaN,2015-04-16 11:31:57,,Tokha,Central Development Region,Bagmati,Danphe Colony Road,44600

In [34]:
import sys  

reload(sys)  
sys.setdefaultencoding('ascii')

In [22]:
df.to_csv("setonelocdf.csv")

In [35]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()
location = geolocator.reverse("27.6988, 85.3774")
location.address

u'F89, \u0915\u093e\u0920\u092e\u093e\u0921\u094c\u0902, \u092c\u093e\u0917\u092e\u0924\u0940 \u0905\u091e\u094d\u091a\u0932, \u092e\u0927\u094d\u092f\u092e\u093e\u091e\u094d\u091a\u0932 \u0935\u093f\u0915\u093e\u0938 \u0915\u094d\u0937\u0947\u0924\u094d\u0930, 9771, \u0928\u0947\u092a\u093e\u0932'

In [18]:
get_address(27.6888,85.3774)

2               Kathmandu
4               Kathmandu
5               Kathmandu
9                   Patan
10        Siddharthanagar
13              Kathmandu
14           Barbhanjyang
16              Kathmandu
17                Baglung
18              Kathmandu
19               Ghandruk
20               Katahari
21              Kathmandu
26              Bharatpur
28                Baglung
29             Ratnanagar
32             Biratnagar
34              Kathmandu
35              Kathmandu
36              Kathmandu
49              Bharatpur
51                 Katari
52              Kathmandu
54              Dandagaun
58              Kathmandu
61              Kathmandu
68              Kathmandu
69              Bharatpur
71              Bharatpur
79              Kathmandu
               ...
183645
183646
183647
183648
183649
183650
183651
183652
183653
183655
183656
183661
183662
183663
183664
183666
183671
183672
183679
183691
183701
183704
183709
183712
183720
183727
183728
183730
183735
183744
Name: city, dtype: object

In [ ]:
https://maps.googleapis.com/maps/api/geocode/json?
    
    components=administrative_area:{NP}|country:&key={key}